# Generated by Django 4.2.26 on 2025-11-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_post_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.IntegerField(choices=[(0, 'Not Private'), (1, 'Private')], default=1),
        ),
    ]
